// One irregular verb. v2/v3 are arrays because some verbs accept two forms.
export type IrregularVerb = { v1: string; v2: string[]; v3: string[] }

// Grouped by SHAPE rather than alphabetically — the shape is the thing worth
// learning, and it gives conjugate.ts a spread of cases to handle.
// If you'd rather the table read A-Z, sort a copy at render time.
export const IrregularVerbs: IrregularVerb[] = [
  // ---- 1. All three forms identical (V1 = V2 = V3) ----
  { v1: 'cut', v2: ['cut'], v3: ['cut'] },
  { v1: 'put', v2: ['put'], v3: ['put'] },
  { v1: 'let', v2: ['let'], v3: ['let'] },
  { v1: 'set', v2: ['set'], v3: ['set'] },
  { v1: 'hit', v2: ['hit'], v3: ['hit'] },
  { v1: 'shut', v2: ['shut'], v3: ['shut'] },
  { v1: 'cost', v2: ['cost'], v3: ['cost'] },
  { v1: 'hurt', v2: ['hurt'], v3: ['hurt'] },
  { v1: 'spread', v2: ['spread'], v3: ['spread'] },
  { v1: 'cast', v2: ['cast'], v3: ['cast'] },
  { v1: 'burst', v2: ['burst'], v3: ['burst'] },
  { v1: 'quit', v2: ['quit'], v3: ['quit'] },
  { v1: 'split', v2: ['split'], v3: ['split'] },
  { v1: 'bet', v2: ['bet'], v3: ['bet'] },
  // Spelled the same in all three, but pronounced /riːd/, /rɛd/, /rɛd/ —
  // the only verb here whose irregularity is invisible in writing.
  { v1: 'read', v2: ['read'], v3: ['read'] },

  // ---- 2. V1 = V3, V2 differs ----
  { v1: 'come', v2: ['came'], v3: ['come'] },
  { v1: 'become', v2: ['became'], v3: ['become'] },
  { v1: 'run', v2: ['ran'], v3: ['run'] },

  // ---- 3. V1 = V2, V3 differs (rare) ----
  { v1: 'beat', v2: ['beat'], v3: ['beaten'] },

  // ---- 4. V2 = V3 (the biggest group) ----
  { v1: 'have', v2: ['had'], v3: ['had'] },
  { v1: 'make', v2: ['made'], v3: ['made'] },
  { v1: 'say', v2: ['said'], v3: ['said'] },
  { v1: 'pay', v2: ['paid'], v3: ['paid'] },
  { v1: 'lay', v2: ['laid'], v3: ['laid'] },
  { v1: 'buy', v2: ['bought'], v3: ['bought'] },
  { v1: 'bring', v2: ['brought'], v3: ['brought'] },
  { v1: 'think', v2: ['thought'], v3: ['thought'] },
  { v1: 'catch', v2: ['caught'], v3: ['caught'] },
  { v1: 'teach', v2: ['taught'], v3: ['taught'] },
  { v1: 'fight', v2: ['fought'], v3: ['fought'] },
  { v1: 'seek', v2: ['sought'], v3: ['sought'] },
  { v1: 'build', v2: ['built'], v3: ['built'] },
  { v1: 'send', v2: ['sent'], v3: ['sent'] },
  { v1: 'spend', v2: ['spent'], v3: ['spent'] },
  { v1: 'lend', v2: ['lent'], v3: ['lent'] },
  { v1: 'bend', v2: ['bent'], v3: ['bent'] },
  { v1: 'feel', v2: ['felt'], v3: ['felt'] },
  { v1: 'keep', v2: ['kept'], v3: ['kept'] },
  { v1: 'sleep', v2: ['slept'], v3: ['slept'] },
  { v1: 'sweep', v2: ['swept'], v3: ['swept'] },
  { v1: 'weep', v2: ['wept'], v3: ['wept'] },
  { v1: 'creep', v2: ['crept'], v3: ['crept'] },
  { v1: 'mean', v2: ['meant'], v3: ['meant'] },
  { v1: 'deal', v2: ['dealt'], v3: ['dealt'] },
  { v1: 'leave', v2: ['left'], v3: ['left'] },
  { v1: 'lose', v2: ['lost'], v3: ['lost'] },
  { v1: 'meet', v2: ['met'], v3: ['met'] },
  { v1: 'sit', v2: ['sat'], v3: ['sat'] },
  { v1: 'feed', v2: ['fed'], v3: ['fed'] },
  { v1: 'lead', v2: ['led'], v3: ['led'] },
  { v1: 'sell', v2: ['sold'], v3: ['sold'] },
  { v1: 'tell', v2: ['told'], v3: ['told'] },
  { v1: 'hold', v2: ['held'], v3: ['held'] },
  { v1: 'find', v2: ['found'], v3: ['found'] },
  { v1: 'bind', v2: ['bound'], v3: ['bound'] },
  { v1: 'wind', v2: ['wound'], v3: ['wound'] },
  { v1: 'grind', v2: ['ground'], v3: ['ground'] },
  { v1: 'stand', v2: ['stood'], v3: ['stood'] },
  { v1: 'understand', v2: ['understood'], v3: ['understood'] },
  { v1: 'hear', v2: ['heard'], v3: ['heard'] },
  { v1: 'hang', v2: ['hung'], v3: ['hung'] },
  { v1: 'dig', v2: ['dug'], v3: ['dug'] },
  { v1: 'win', v2: ['won'], v3: ['won'] },
  { v1: 'shoot', v2: ['shot'], v3: ['shot'] },
  { v1: 'shine', v2: ['shone'], v3: ['shone'] },
  { v1: 'strike', v2: ['struck'], v3: ['struck'] },
  { v1: 'flee', v2: ['fled'], v3: ['fled'] },
  { v1: 'light', v2: ['lit'], v3: ['lit'] },
  // British 'got' vs American 'gotten' — both current, so both are listed.
  { v1: 'get', v2: ['got'], v3: ['got', 'gotten'] },

  // ---- 5. All three differ ----
  { v1: 'go', v2: ['went'], v3: ['gone'] },
  { v1: 'do', v2: ['did'], v3: ['done'] },
  { v1: 'see', v2: ['saw'], v3: ['seen'] },
  { v1: 'eat', v2: ['ate'], v3: ['eaten'] },
  { v1: 'give', v2: ['gave'], v3: ['given'] },
  { v1: 'take', v2: ['took'], v3: ['taken'] },
  { v1: 'write', v2: ['wrote'], v3: ['written'] },
  { v1: 'drive', v2: ['drove'], v3: ['driven'] },
  { v1: 'ride', v2: ['rode'], v3: ['ridden'] },
  { v1: 'rise', v2: ['rose'], v3: ['risen'] },
  { v1: 'speak', v2: ['spoke'], v3: ['spoken'] },
  { v1: 'break', v2: ['broke'], v3: ['broken'] },
  { v1: 'choose', v2: ['chose'], v3: ['chosen'] },
  { v1: 'steal', v2: ['stole'], v3: ['stolen'] },
  { v1: 'freeze', v2: ['froze'], v3: ['frozen'] },
  { v1: 'wake', v2: ['woke'], v3: ['woken'] },
  { v1: 'weave', v2: ['wove'], v3: ['woven'] },
  { v1: 'know', v2: ['knew'], v3: ['known'] },
  { v1: 'grow', v2: ['grew'], v3: ['grown'] },
  { v1: 'throw', v2: ['threw'], v3: ['thrown'] },
  { v1: 'blow', v2: ['blew'], v3: ['blown'] },
  { v1: 'fly', v2: ['flew'], v3: ['flown'] },
  { v1: 'draw', v2: ['drew'], v3: ['drawn'] },
  { v1: 'begin', v2: ['began'], v3: ['begun'] },
  { v1: 'drink', v2: ['drank'], v3: ['drunk'] },
  { v1: 'sing', v2: ['sang'], v3: ['sung'] },
  { v1: 'ring', v2: ['rang'], v3: ['rung'] },
  { v1: 'swim', v2: ['swam'], v3: ['swum'] },
  { v1: 'sink', v2: ['sank'], v3: ['sunk'] },
  { v1: 'spring', v2: ['sprang'], v3: ['sprung'] },
  { v1: 'shrink', v2: ['shrank'], v3: ['shrunk'] },
  { v1: 'forget', v2: ['forgot'], v3: ['forgotten'] },
  { v1: 'forgive', v2: ['forgave'], v3: ['forgiven'] },
  { v1: 'fall', v2: ['fell'], v3: ['fallen'] },
  { v1: 'wear', v2: ['wore'], v3: ['worn'] },
  { v1: 'tear', v2: ['tore'], v3: ['torn'] },
  { v1: 'swear', v2: ['swore'], v3: ['sworn'] },
  { v1: 'hide', v2: ['hid'], v3: ['hidden'] },
  { v1: 'bite', v2: ['bit'], v3: ['bitten'] },
  // 'was' and 'were' aren't stylistic variants like learned/learnt — they
  // split by person and number (I was / they were). The table can only show
  // both; choosing between them is grammar the lookup doesn't model.
  { v1: 'be', v2: ['was', 'were'], v3: ['been'] },

  // ---- 6. Two accepted forms: a regular -ed and an irregular -t ----
  // The -t forms are the usual British spelling, -ed the American one.
  { v1: 'learn', v2: ['learned', 'learnt'], v3: ['learned', 'learnt'] },
  { v1: 'dream', v2: ['dreamed', 'dreamt'], v3: ['dreamed', 'dreamt'] },
  { v1: 'burn', v2: ['burned', 'burnt'], v3: ['burned', 'burnt'] },
  { v1: 'spell', v2: ['spelled', 'spelt'], v3: ['spelled', 'spelt'] },
  { v1: 'smell', v2: ['smelled', 'smelt'], v3: ['smelled', 'smelt'] },
  { v1: 'spill', v2: ['spilled', 'spilt'], v3: ['spilled', 'spilt'] },
  { v1: 'leap', v2: ['leaped', 'leapt'], v3: ['leaped', 'leapt'] },
  { v1: 'kneel', v2: ['kneeled', 'knelt'], v3: ['kneeled', 'knelt'] },
  // Regular V2, irregular V3 — the -n participle is the standard one.
  { v1: 'show', v2: ['showed'], v3: ['shown', 'showed'] },
  { v1: 'prove', v2: ['proved'], v3: ['proven', 'proved'] },
]
